### ISSUE TITLE
How to download the DCASE dataset?

### ISSUE THREAD

**Issue by fake-warrior8** [facebookresearch/AVID-CMA#10]
Hi, I'd like to known how to download the DCASE dataset. I found that there are many versions of DCASE dataset on their website [DCASE](https://dcase.community/challenge2017/download#task-1---acoustic-scene-classification), and I don't know to download each one version.

**Comment by pedro-morgado** [comment]
For fair comparison to prior work, we used the Acoustic Scenes 2013 version.
https://dcase.community/challenge2013/task-acoustic-scene-classification

**Comment by fake-warrior8** [comment]
> For fair comparison to prior work, we used the Acoustic Scenes 2013 version. https://dcase.community/challenge2013/task-acoustic-scene-classification

That is it. Thanks!

**Comment by fake-warrior8** [comment]
> For fair comparison to prior work, we used the Acoustic Scenes 2013 version. https://dcase.community/challenge2013/task-acoustic-scene-classification

I downloaded the public(validation) dataset and the private(train/test) dataset, both with 100 records. The official website says that they will use a  5-fold stratified cross validation. Does this mean that the private dataset will be randomly divided into 80 records for training and another 20 records for testing?
